name: Build & test
on:
  push:
    tags:
      - ci*

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           cache: 'yarn'
#           node-version: 16.10.0
      - uses: bahmutov/npm-install@v1.8.25
        with: { useRollingCache: true } # recommended for large projects
        env:
          CYPRESS_INSTALL_BINARY: 0 # no need to install the Cypress binary, we are already using the docker image in the e2e job
      # - name: Reset coverage (Coverage_step1)
      # reset state at the beginning for new unit + e2e coverage evaluation
      # run: yarn cov:reset

  unit-test:
    needs: [install-dependencies]
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1.8.25
        with: { useRollingCache: true }
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: unit-test
        run: npm run ci:test

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: coverage
          path: coverage/
          retention-days: 1

  
